# Generated by Django 5.0.6 on 2025-04-18 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CricketMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teams', models.CharField(max_length=100)),
                ('tournament', models.CharField(max_length=100)),
                ('score', models.CharField(max_length=100)),
                ('sport', models.CharField(default='cricket', max_length=50)),
            ],
        ),
    ]
